### ISSUE TITLE
`hash` is `undefined` in `ajaxOptions`

### ISSUE THREAD

**Issue by martinmaillard** [funtusov/ember-cli-form-data#1]
In some cases, the `hash` argument in `ajaxOptions` is undefined. Wouldn't it be better to first call the `_super` method and then modify the result ? Something like:

    ajaxOptions: function(url, type, options) {
      var hash = this._super.apply(this, arguments);

      if (hash.data && this.formDataTypes.contains(type)) {
        hash = this._setBaseFor(url, type, hash, this);
        hash = this._setFormDataFor(hash);
        hash = this._setHeadersFor(hash);
      }

      return hash;
    },

What do you think ?

**Comment by funtusov** [comment]
@martinmaillard good catch, and I like that it removes a branch from the code. I'll add it to the next update, thanks.

**Comment by funtusov** [comment]
Actually, a lot of the code did duplicate the default ``ajaxOptions`` method, I decided to use the latter as much as possible. 

https://github.com/funtusov/ember-cli-form-data/commit/7348dc08e412170b7d4d6237d34e3a084c1a6207

**Comment by martinmaillard** [comment]
Hum... so it might not have been the best suggestion... `ajaxOptions` seems to be processing (modifying) the data. If you use the `RESTAdapter` for example, calling `_super` will serialize the data to string, which breaks `_setFormDataFor`. Sorry about that...

**Comment by funtusov** [comment]
I don't think it serializes it to string:

```js
> DS.RESTAdapter.create().ajaxOptions()
> Object {url: undefined, type: undefined, dataType: "json", context: n}
```
