### ISSUE TITLE
Empty file being uploaded

### ISSUE THREAD

**Issue by kgish** [funtusov/ember-cli-form-data#11]
I'm trying to implement `ember-cli-form-data` to upload a file to my rails backend server which is using the `CarrierWave` gem.

I followed your guidelines step by step but cannot get it to work properly.

In the request, the file is empty for some weird reason.
```
file => {}
```
I'm using the following versions:
```
Ember:      1.13.7
Ember data: 1.13.8
```
Could it be that `ember-cli-form-data` doesn't work for these versions?

**Comment by funtusov** [comment]
Hi, it should be working for those versions if I remember correctly. Could you please show the code that sets the file property on the model?

**Comment by kgish** [comment]
Here's the code that I am using:

**app/adapters/upload.js**
```javascript
import ApplicationAdapter from './application';
import FormDataAdapterMixin from 'ember-cli-form-data/mixins/form-data-adapter';

export default ApplicationAdapter.extend(FormDataAdapterMixin, {
});
```
**app/models/upload.js**
```javascript
import DS from 'ember-data';

export default DS.Model.extend({
    name: DS.attr('string'),
    bucket: DS.attr('string'),
    file: DS.attr('file')
});
```
**app/templates/uploads/-form.hbs**
```javascript
<form class="form-horizontal">
    <div class="form-group">
        <label class="control-label col-sm-1" for="name">Name:</label>
        <div class="col-sm-10">
            {{input type="text" class="form-control" id="name" value=model.name}}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-1" for="bucket">Bucket:</label>
        <div class="col-sm-10">
            {{input type="text" class="form-control" id="bucket" value=model.bucket}}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-1" for="file">File:</label>
        <div class="col-sm-10">
            {{input type="file" class="form-control" id="file-field" value=model.file}}
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-1 col-sm-11">
            <button type="button" class="btn btn-primary btn-sm" title="Save" {{action 'save'}}>
                {{fa-icon 'check'}} Save
            </button>
            <button type="button" class="btn btn-default btn-sm" title="Cancel" {{action 'cancel'}}>
                {{fa-icon 'close'}} Cancel
            </button>
        </div>
    </div>
</form>
```
**app/controllers/uploads/new.js**
```javascript
import Ember from 'ember';

export default Ember.Controller.extend({
    ...
    actions: {
        save: function() {
            var _this = this,
                currentModel = this.currentModel;
            var file = document.getElementById('file-field').files[0];
            currentModel.set('file', file);
            currentModel.save().then(
                function() {
                    _this.transitionTo(_this.routeName.split('.')[0]);
                },
                function() {
                    console.log('UploadsSaveModelMixin: currentModel.save() failed!');
                }
            );
        },
});
```
When I try to send it to the server, the request has the following payload:
```
{"upload":{"name":"A new file","bucket":"images","file":{}}}
```
As you can see there is something wrong with `file`

**Comment by kgish** [comment]
I tried changing the form to include an enctype attribute like this:
```
<form class="form-horizontal" enctype="multipart/form-data">
    ...
</form
```
But get the following error message:
```
Uncaught InvalidStateError: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.
```

**Comment by funtusov** [comment]
Hmm, that's odd, the code looks fine. Could you check the file property of the model via the ember inspector?

**Comment by kgish** [comment]
What do you mean 'the file property' of the model, where?

**Comment by kgish** [comment]
See above:
```
File {}
    lastModified: 1443087272282
    lastModifiedDate: Thu Sep 24 2015 11:34:32 GMT+0200 (West-Europa (zomertijd))
    name: "bender-1.png"
    size: 21087
    type: "image/png"
    webkitRelativePath: ""
    __proto__: File
```

**Comment by kgish** [comment]
![image](https://cloud.githubusercontent.com/assets/79195/10082938/7756648c-62fc-11e5-90b7-91d7fd9e839d.png)


![image](https://cloud.githubusercontent.com/assets/79195/10082877/34c22b6a-62fc-11e5-906c-8457e86b2242.png)

![image](https://cloud.githubusercontent.com/assets/79195/10082915/5e0a4ba6-62fc-11e5-8f59-00162760e5bf.png)

**Comment by funtusov** [comment]
I was referring to the "file" attribute of the model in question, as seen
in the Ember Data tab of Ember Inspector. If the attributes screenshot is
from there, it seems that the "file" attribute is not being set for some
reason.

This module works by sending the content of the "file" property as a
FormData item, but if the property isn't populated, it won't be able to do
so.

I would debug that by launching the console, loading the currentModel as
$E, and then doing something like $E.set('file',
document.getElementById......), and then seeing if $E.get('file') contains
something, if it does – $E.save() and check the request object.

2015-09-24 21:40 GMT+03:00 Kiffin Gish <notifications@github.com>:

**Comment by kgish** [comment]
I followed the instructions from your previous comment, and this is what I see:

![image](https://cloud.githubusercontent.com/assets/79195/10083815/5227c828-6300-11e5-80c7-eb6797e456e4.png)

**Comment by kgish** [comment]
Maybe this will help. According to the specs, the `files` property of `HTMLInputElement` is **readonly**.

See: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement

Perhaps this is just a Chrome issue, I am not sure.

**Comment by kgish** [comment]
I just tried it with Firefox and have the same problem.

Have you recently tested on the latest browsers?

**Comment by kgish** [comment]
Lo and behold, I finally figured out what the problems is.

In my template `-form.hbs` above, the following line:
```
{{input type="file" class="form-control" id="file-field" value=model.file}}
```
needs to be replaced by:
```
{{input type="file" class="form-control" id="file-field"}}
```
e.g. the `value=model.file` is not allowed.

Now everything works like a whistle, thanks!

**Comment by funtusov** [comment]
Glad you solved it out! Thanks for posting!
