### ISSUE TITLE
payload is not json

### ISSUE THREAD

**Issue by acerov** [funtusov/ember-cli-form-data#13]
Hi,
Thank you for your effort but I am having some trouble,
I have simple form with just one field, on POST request instead of json I am getting something like:
------WebKitFormBoundary57pDcluXygbVh10c
Content-Disposition: form-data; name="config[myPropertyName]"; filename="test.txt"
Content-Type: application/octet-stream

------WebKitFormBoundary57pDcluXygbVh10c--
If I inspect file object in console it looks ok, even in my model it is there.

**Comment by funtusov** [comment]
Well, this is FormData (https://developer.mozilla.org/en/docs/Web/API/FormData), exactly what this addon aims to send :)
