### ISSUE TITLE
version is not updated

### ISSUE THREAD

**Issue by praya** [funtusov/ember-cli-form-data#27]
Source files are updated, but version is not updated, version of npm package is still the same 1.1.0 (published a year ago).
Please publish the changes.

**Comment by rmachielse** [comment]
@funtusov any chance of a release soon? Master already contains the needed updates to get rid of the ember-cli-babel deprecation. Would be great if this can get a release!

**Comment by alanlalonde** [comment]
@funtusov I'll echo this: Any news on setting up a new release? Apparently this deprecation warning will become a full-on error in a minor version of ember-cli, not just a major version. It could break at any time in the future. https://github.com/offirgolan/ember-cp-validations/issues/575

**Comment by funtusov** [comment]
Sorry for the wait, just published `1.2.0`

**Comment by alanlalonde** [comment]
Thanks!

**Comment by synaptiko** [comment]
@funtusov I was a bit puzzled, I found `1.2.0` in npm repo but there is neither tag nor relase with this version present in this repository (https://github.com/funtusov/ember-cli-form-data/releases) and `package.json` on `master` still says it's `1.1.0`: https://github.com/funtusov/ember-cli-form-data/blob/master/package.json#L3

I think this can confuse package managers a bit. Could you please create patch version which will update `package.json`, create a tag and then publish it on npm? Thank you :-)
